<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategory()
    {
        return $this->createQueryBuilder('category')->addOrderBy('category.id')->getQuery()->getResult();
    }

    public function getCategoryArray()
    {
        $date = $this->createQueryBuilder('Category')->orderBy('Category.name')->getQuery()->getResult();
        $arrayRez = [];

        foreach ($date as $value){
            $arrayRez[$value->getName()] = $value->getId();
        }
//        $arrayRez = array_flip($arrayRez);
        return $arrayRez;
    }
}
