<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCommentsForNews($id, $visible = true)
    {
        $comments = $this->createQueryBuilder('comment')
            ->where("comment.news = $id")
            ->andWhere("comment.parent is NULL")
            ->andWhere("comment.visible = (:visible) OR comment.visible = true")
            ->addOrderBy('comment.date', 'DESC')
            ->setParameter('visible', $visible)
            ->getQuery()
            ->getResult();
        $arrayComments = [];

        foreach ($comments as  $key=>$value){
            $arrayComments[] = ['data' => $value, 'child' => $this->getChildComments($value->getId(), $visible)];
        }

        return $arrayComments;
    }

    public function getChildComments($parentId, $visible = true)
    {
        $comments = $this->createQueryBuilder('comment')
            ->where("comment.parent = $parentId")
            ->andWhere("comment.visible = (:visible) OR comment.visible = true")
            ->addOrderBy('comment.date', 'ASC')
            ->setParameter('visible', $visible)
            ->getQuery()
            ->getResult();

        $arrayComments = [];

        foreach ($comments as $value){
            $arrayComments[] = ['data' => $value, 'child' => $this->getChildComments($value->getId(), $visible)];
        }

        return $arrayComments;
    }
}
