<?php

namespace AppBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    //test
    public function getRating($comment_id, $user_id)
    {
        $rating = $this->createQueryBuilder('rating')
            ->where('rating.commentId = :comment')
            ->andWhere('rating.userId = :user')
            ->setParameters(['comment' => $comment_id,
                'user' => $user_id])
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
        return $rating;
    }
}
