<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTag()
    {
        return $this->createQueryBuilder('tag')->addOrderBy('tag.id')->getQuery()->getResult();
    }

    public function getTagArray()
    {
        $date = $this->createQueryBuilder('Tag')->orderBy('Tag.name')->getQuery()->getResult();
        $arrayRez = [];

        foreach ($date as $value){
            $arrayRez[$value->getName()] = $value->getId();
        }
//        $arrayRez = array_flip($arrayRez);
        return $arrayRez;
    }

    public function getTagByName($name = 'mas')
    {
        $tags = $this->createQueryBuilder('tag')
            ->select('tag.id')
            ->addSelect('tag.name')
            ->where('tag.name like :name')
            ->setParameter('name','%' . $name . '%')
            ->orderBy('tag.name')
            ->getQuery()
            ->getResult();

//        foreach ($tags as $value){
//            $rez[$value->getId()] = $value->getName();
//        }

        return $tags;
    }

}
